ALTER TABLE answers
ADD COLUMN IF NOT EXISTS main_snippet TEXT,
ADD COLUMN IF NOT EXISTS mentions_brand BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS confidence REAL,
ADD COLUMN IF NOT EXISTS parsed_at TIMESTAMPTZ;
